blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Support
    url: andras@gregorigin.com
    url: https://forums.unrealengine.com/t/gregorigin-sonant-native-contextual-audio-middleware/2684588
    about: Please ask general questions or feature requests here.
  - name: ðŸ“š Documentation
    url: https://gregorigin.gitbook.io/sonant-docs
    about: Read the manual before reporting a bug.
